### ISSUE TITLE
Replace the panic!() to eprintln!()

### ISSUE THREAD

**Issue by mustakimur** [ChinmayDeosthali/Rust-Compiler#4]
@ChinmayDeosthali @ellezeeman @Chinmaykd21 please check the recent announcement which I had also briefed earlier in the class.

**Comment by mustakimur** [comment]
Replace the following panic!():
```rust
let mut file = match File::open(&args[1]) {
                Ok(file) => file,
                Err(why) => panic!("\n\n{}:{}\n\n", why, &args[1]),
            };
```
with
```rust
let mut file = match File::open(&args[1]) {
                Ok(file) => file,
                Err(why) => match why.kind() {
                    ErrorKind::NotFound => {
                        eprintln!("File not found");
                        process::exit(0);
                    }
                    ErrorKind::PermissionDenied => {
                        eprintln!("File permission denied");
                        process::exit(0);
                    }
                    _ => {
                        eprintln!("other errors {}", why);
                        process::exit(0);
                    }
                },
            };
```

The above is the best practice.

**Comment by Chinmaykd21** [comment]
Thank you, Professor. This is helpful. We will update accordingly.

**Comment by ellezeeman** [comment]
<img width="987" alt="Screen Shot 2021-04-30 at 2 15 15 PM" src="https://user-images.githubusercontent.com/54867536/116736879-8084cf80-a9be-11eb-9afa-c817758a3135.png">

Professor, 

I have fixed the issue and will release the updated version soon.
Thank you for your help!

**Comment by mustakimur** [comment]
if so, you can close the issue.

**Comment by ellezeeman** [comment]
Issue was fixed and committed, refer to commit ID as mentioned above.
